# Generated by Django 3.2 on 2025-07-30 10:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_product_purchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='change_price',
            new_name='purchase_rate',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='final_price',
            new_name='selling_price',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='date',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='description',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='product_rate',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='total_price',
        ),
        migrations.AddField(
            model_name='purchase',
            name='discount_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
