# Generated by Django 3.2 on 2025-07-31 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20250730_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='purchase_rate',
            new_name='change_price',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='selling_price',
            new_name='product_rate',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='discount_rate',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
