# Generated by Django 3.2 on 2025-08-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20250731_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='sale_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
