# Generated by Django 3.2 on 2025-08-02 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_purchase_sale_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sellingproduct',
            options={'ordering': ['-date_added']},
        ),
    ]
