# Generated by Django 3.2 on 2025-08-02 15:48

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_sellingproduct_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('gst_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('roundoff', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('final_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('final', 'Finalized'), ('cancelled', 'Cancelled')], default='draft', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('billing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='income', to='user.billing')),
            ],
        ),
        migrations.CreateModel(
            name='BillingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='user.billing')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.product')),
            ],
        ),
    ]
