# Generated by Django 3.2 on 2025-08-02 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_billing_billingitem_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.purchase'),
        ),
    ]
