# Generated by Django 3.2 on 2025-08-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20250803_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='customer_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='customer_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
