# Generated by Django 3.2 on 2025-08-26 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20250803_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='bill_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
