# Generated by Django 3.2 on 2025-08-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_billing_bill_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billingitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
