# Generated by Django 3.2 on 2025-08-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20250826_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
