# Generated by Django 3.2 on 2025-08-26 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_alter_billingitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='bill_number',
        ),
    ]
