# Generated by Django 3.2 on 2025-08-29 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_auto_20250829_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='product',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='purchase',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='user.purchase'),
            preserve_default=False,
        ),
    ]
