# Generated by Django 3.2 on 2025-09-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_auto_20250829_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
