# Generated by Django 3.2 on 2025-09-12 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_purchase_expire_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='gst_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='gst_percent',
        ),
    ]
