# Generated by Django 3.2 on 2025-09-17 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='Stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.stock'),
        ),
    ]
