# Generated by Django 3.2 on 2025-09-17 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_purchase_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='Stock',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
