# Generated by Django 3.2 on 2025-10-20 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('category', 'name')},
        ),
    ]
