# Generated by Django 3.2 on 2025-10-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_auto_20251022_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
