# Generated by Django 5.1.5 on 2026-02-28 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_seed_india_baseline'),
        ('nearshop', '0003_product_deleted_at_product_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shops', to='locations.country'),
        ),
        migrations.AddField(
            model_name='shop',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shops', to='locations.district'),
        ),
        migrations.AddField(
            model_name='shop',
            name='locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shops', to='locations.locality'),
        ),
        migrations.AddField(
            model_name='shop',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shops', to='locations.state'),
        ),
    ]
