# Generated by Django 5.1.5 on 2026-02-28 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_shop_categories(apps, schema_editor):
    ShopCategory = apps.get_model('nearshop', 'ShopCategory')
    Shop = apps.get_model('nearshop', 'Shop')

    defaults = [
        ('Grocery', 'Daily essentials and groceries.'),
        ('Bakery', 'Bread, cakes, and baked products.'),
        ('Pharmacy', 'Medicines and wellness products.'),
        ('Electronics', 'Gadgets and electronics.'),
        ('Fashion', 'Clothing and fashion products.'),
        ('Hardware', 'Hardware and tools.'),
    ]
    for name, description in defaults:
        ShopCategory.objects.get_or_create(name=name, defaults={'description': description, 'is_active': True})

    for shop in Shop.objects.filter(category__isnull=True).exclude(shop_category='').iterator():
        existing = ShopCategory.objects.filter(name__iexact=shop.shop_category).first()
        if existing:
            shop.category_id = existing.id
            shop.save(update_fields=['category'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('nearshop', '0004_shop_country_shop_district_shop_locality_shop_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='shop',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shops', to='nearshop.shopcategory'),
        ),
        migrations.CreateModel(
            name='ShopCategoryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('admin_note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_category_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(seed_shop_categories, noop_reverse),
    ]
