# Generated by Django 3.2 on 2025-10-23 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_subcategory_name'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='custom_design_image',
            field=models.ImageField(blank=True, null=True, upload_to='custom_designs/'),
        ),
        migrations.AddField(
            model_name='booking',
            name='district',
            field=models.CharField(default='Kasaragod', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='house_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='booking',
            name='pincode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='place',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='state',
            field=models.CharField(default='Kerala', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='design',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.design'),
        ),
    ]
