# Generated by Django 3.2 on 2025-10-23 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20251024_0043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['start_time']},
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='date',
        ),
    ]
