# Generated by Django 3.2 on 2025-10-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20251024_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_option',
            field=models.CharField(choices=[('full', 'Full Payment'), ('advance', 'Advance Payment (40%)')], default='full', max_length=10),
        ),
    ]
