# Generated by Django 3.2 on 2025-10-23 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_subcategory_name'),
        ('booking', '0008_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.category'),
        ),
        migrations.AddField(
            model_name='booking',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.subcategory'),
        ),
    ]
