# Generated by Django 5.1.5 on 2026-02-28 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('code', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('external_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='locations_c_name_b70dbe_idx')],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(blank=True, max_length=16, null=True)),
                ('external_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='states', to='locations.country')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(blank=True, max_length=16, null=True)),
                ('external_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='districts', to='locations.state')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('pincode', models.CharField(blank=True, max_length=12)),
                ('external_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='localities', to='locations.district')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['district', 'name'], name='locations_l_distric_ec9370_idx'), models.Index(fields=['name'], name='locations_l_name_79dc2e_idx'), models.Index(fields=['pincode'], name='locations_l_pincode_17646c_idx')],
                'constraints': [models.UniqueConstraint(fields=('district', 'name', 'pincode'), name='unique_locality_per_district')],
            },
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['country', 'name'], name='locations_s_country_ef6e7b_idx'),
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['name'], name='locations_s_name_5adbc5_idx'),
        ),
        migrations.AddConstraint(
            model_name='state',
            constraint=models.UniqueConstraint(fields=('country', 'name'), name='unique_state_per_country'),
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['state', 'name'], name='locations_d_state_i_19ead7_idx'),
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['name'], name='locations_d_name_f8f0e0_idx'),
        ),
        migrations.AddConstraint(
            model_name='district',
            constraint=models.UniqueConstraint(fields=('state', 'name'), name='unique_district_per_state'),
        ),
    ]
