# Generated by Codex on 2026-02-28

from django.db import migrations


STATE_NAMES = [
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chhattisgarh",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal",
    "Andaman and Nicobar Islands",
    "Chandigarh",
    "Dadra and Nagar Haveli and Daman and Diu",
    "Delhi",
    "Jammu and Kashmir",
    "Ladakh",
    "Lakshadweep",
    "Puducherry",
]


def seed_baseline_locations(apps, schema_editor):
    Country = apps.get_model("locations", "Country")
    State = apps.get_model("locations", "State")
    District = apps.get_model("locations", "District")
    Locality = apps.get_model("locations", "Locality")

    india, _ = Country.objects.get_or_create(
        code="IN",
        defaults={"name": "India", "external_id": "country_in"},
    )

    for state_name in STATE_NAMES:
        state, _ = State.objects.get_or_create(
            country_id=india.id,
            name=state_name,
            defaults={"external_id": f"state_{state_name.lower().replace(' ', '_')}"},
        )
        district, _ = District.objects.get_or_create(
            state_id=state.id,
            name=f"{state_name} Central",
            defaults={"external_id": f"district_{state_name.lower().replace(' ', '_')}_central"},
        )
        Locality.objects.get_or_create(
            district_id=district.id,
            name="Central",
            pincode="",
            defaults={"external_id": f"locality_{state_name.lower().replace(' ', '_')}_central"},
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_baseline_locations, noop_reverse),
    ]
