# Generated by Django 5.1.5 on 2026-02-28 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_seed_india_baseline'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='locality',
            name='unique_locality_per_district',
        ),
    ]
