# Generated by Django 3.2 on 2025-10-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='event_type',
            field=models.CharField(choices=[('wedding', 'Wedding'), ('party', 'Party'), ('festival', 'Festival'), ('other', 'Other')], default='wedding', max_length=20),
        ),
    ]
