# Generated by Django 3.2 on 2025-10-23 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_payment_payment_method'),
        ('admin_panel', '0002_feedback_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.booking'),
        ),
    ]
