# Generated by Django 3.2 on 2025-10-23 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_feedback_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='event_type',
        ),
    ]
