# Generated by Django 5.1.5 on 2026-02-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nearride', '0002_driverprofile_is_blocked_driverprofile_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
