# Generated by Django 5.1.5 on 2026-02-28 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_seed_india_baseline'),
        ('nearride', '0003_riderequest_deleted_at_riderequest_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='drivers', to='locations.country'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='drivers', to='locations.district'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='drivers', to='locations.locality'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='service_area_scope',
            field=models.CharField(choices=[('specific', 'Given Location'), ('all', 'All Locations')], default='specific', max_length=16),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='drivers', to='locations.state'),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='destination_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destination_rides', to='locations.country'),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='destination_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destination_rides', to='locations.district'),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='destination_locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destination_rides', to='locations.locality'),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='destination_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destination_rides', to='locations.state'),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='pickup_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pickup_rides', to='locations.country'),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='pickup_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pickup_rides', to='locations.district'),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='pickup_locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pickup_rides', to='locations.locality'),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='pickup_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pickup_rides', to='locations.state'),
        ),
    ]
