# Generated by Django 5.1.5 on 2026-02-28 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_ride_categories(apps, schema_editor):
    RideCategory = apps.get_model('nearride', 'RideCategory')
    DriverProfile = apps.get_model('nearride', 'DriverProfile')
    RideRequest = apps.get_model('nearride', 'RideRequest')

    defaults = [
        ('Bike', 'Affordable two-wheeler rides.'),
        ('Auto Rickshaw', 'City auto rickshaw rides.'),
        ('Car', 'Standard car rides.'),
        ('Premium', 'Premium comfort rides.'),
    ]
    for name, description in defaults:
        RideCategory.objects.get_or_create(name=name, defaults={'description': description, 'is_active': True})

    bike = RideCategory.objects.filter(name='Bike').first()
    auto = RideCategory.objects.filter(name='Auto Rickshaw').first()
    car = RideCategory.objects.filter(name='Car').first()

    vehicle_map = {
        'bike': bike,
        'auto': auto,
        'car': car,
    }
    for profile in DriverProfile.objects.filter(ride_category__isnull=True).iterator():
        mapped = vehicle_map.get(profile.vehicle_type, car)
        if mapped:
            profile.ride_category_id = mapped.id
            profile.save(update_fields=['ride_category'])

    for ride in RideRequest.objects.filter(ride_category__isnull=True).iterator():
        mapped = vehicle_map.get(ride.ride_type, car)
        if mapped:
            ride.ride_category_id = mapped.id
            ride.save(update_fields=['ride_category'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('nearride', '0004_driverprofile_country_driverprofile_district_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RideCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='ride_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='drivers', to='nearride.ridecategory'),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='ride_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ride_requests', to='nearride.ridecategory'),
        ),
        migrations.CreateModel(
            name='RideCategoryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('admin_note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_category_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(seed_ride_categories, noop_reverse),
    ]
