# Generated by Django 5.1.5 on 2026-03-07 05:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nearride', '0005_ridecategory_driverprofile_ride_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driverprofile',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='phone_number',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='driver_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_rides', to='nearride.driverprofile'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
