# Generated by Django 5.1.5 on 2026-03-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nearride', '0006_alter_driverprofile_options_driverprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='completion_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='deletion_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=16),
        ),
    ]
