# Generated by Django 5.1.5 on 2026-03-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nearride', '0007_riderequest_cancel_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderequest',
            name='status',
            field=models.CharField(choices=[('requested', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=16),
        ),
    ]
