# Generated by Django 5.1.5 on 2026-02-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nearservice', '0002_serviceprovider_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
