# Generated by Django 5.1.5 on 2026-02-28 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('nearservice', '0004_servicecategoryrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_providers', to='locations.country'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_providers', to='locations.district'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_providers', to='locations.locality'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_providers', to='locations.state'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='location_text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
