# Generated by Django 5.1.5 on 2026-02-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nearservice', '0005_serviceprovider_country_serviceprovider_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='service_area_scope',
            field=models.CharField(choices=[('specific', 'Given Location'), ('all', 'All Locations')], default='specific', max_length=16),
        ),
    ]
